name: vyatsu_schedule
description: VyatSU schedule Flutter app.

publish_to: 'none'

version: 0.1.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.12.2
  provider: ^3.0.0
  sqflite: ^1.3.0
  path: any
  path_provider: ^1.6.11

  cupertino_icons: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true
